EZRecipize/Controllers/CookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EZRecipize.Models;

namespace EZRecipize.Controllers
{
    public class CookingController : Controller
    {
        //private RecipeDBContext _db;
        private static Recipe recipe;
        private static DisplayInfo Info = new DisplayInfo();
        private static int stepNum = 0;

        public IActionResult Index(int rId)
        {
            recipe =  Repo.recipes.Where(r => r.Id == rId).FirstOrDefault();
            return View(recipe);
        }

        public IActionResult Tutorial()
        {
            if(stepNum < recipe.Steps.Count())
            {
                Info.step = recipe.Steps.ElementAt(stepNum);
                if(Info.step.IsTimer)
                {
                    Info.timers.TryAdd(Info.step.TimerName, Info.step.Timer);
                }
                stepNum++;

                return View(Info);
            }
            else
            {
                stepNum = 0;
                Info = new DisplayInfo();
                return View("Finshed", recipe.Id);
            }

        }


        //protected void Display()
        //{
        //    TimeSpan ts;

        //    HidH.Value = Convert.ToString(ts.Hours);

        //    HidM.Value = Convert.ToString(ts.Minutes);

        //    HidS.Value = Convert.ToString(ts.Seconds);

        //}
            
    }
}

EZRecipize/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EZRecipize.Models;

namespace EZRecipize.Controllers
{
    public class RecipeController : Controller
    {
        //private RecipeDBContext _db;
        private static Recipe recipe;
        private static RecipeStep recipeStep;

        public IActionResult Recipes()
        {
            return View(Repo.recipes);
        }

        //public IActionResult RecipeDetails(Recipe r)
        //{
        //    return View(r);
        //}

        public IActionResult RecipeDetails(int recipeId)
        {
            Recipe r = Repo.recipes.Where(r => r.Id == recipeId).FirstOrDefault();
            return View(r);
        }

        public IActionResult RecipeCooking()
        {
            return View();
        }

        public IActionResult Create(bool active)
        {
            if(!active)
            {
                recipe = new Recipe();
            }

            return View(recipe);
        }

        [HttpPost]
        public IActionResult Create(Recipe recipeTemp, bool addingStep)
        {
            if (ModelState.IsValid && !addingStep && recipe.Steps.Count != 0)
            {
                if(recipe.Steps != null && recipe.Steps.Count > 0)
                {
                    recipe.Steps.Last().SeperateListStrings();
                }
                recipeTemp.Steps = recipe.Steps;
                Repo.recipes.Add(recipeTemp);
                return View("RecipeDetails", recipeTemp);
            }
            else if(addingStep)
            {
                return RedirectToAction("CreateStep", recipeTemp);
            }
            else
            {
                return View(recipe);
            }
        }

        public IActionResult CreateStep(Recipe r, bool active = false)
        {

            if (!active)
            {
                recipeStep = new RecipeStep();
            }
            
            recipe.RecipeName = r.RecipeName;
            recipe.RecipeDescription = r.RecipeDescription;
            if(recipeStep.RequiredCookware == null)
            {
                recipeStep.RequiredCookware = new List<string>();
            }
            if(recipeStep.SuggestedCookware == null)
            {
                recipeStep.SuggestedCookware = new List<string>();
            }
            return View(recipeStep);
        }

        [HttpPost]
        public IActionResult CreateStep(RecipeStep s, bool addingIngredient)
        {
            if (ModelState.IsValid && !addingIngredient)
            {
                recipeStep.TempRequiredCookware = s.TempRequiredCookware;
                recipeStep.TempSuggestedCookware = s.TempSuggestedCookware;
                recipeStep.SeperateListStrings();
                recipeStep.Instructions = s.Instructions;
                recipeStep.IsTimer = s.IsTimer;
                recipeStep.Timer = s.Timer;
                recipeStep.TimerName = s.TimerName;
                

                recipe.Steps.Add(recipeStep);
                return View("Create", recipe);
            }
            else if(addingIngredient)
            {
                recipeStep.TempRequiredCookware = s.TempRequiredCookware;
                recipeStep.TempSuggestedCookware = s.TempSuggestedCookware;
                recipeStep.SeperateListStrings();
                recipeStep.Instructions = s.Instructions;
                recipeStep.IsTimer = s.IsTimer;
                recipeStep.Timer = s.Timer;
                recipeStep.TimerName = s.TimerName;
                recipeStep.TempRequiredCookware = s.TempRequiredCookware;

                return RedirectToAction("CreateIngredient", recipeStep);
            }
            else
            {
                return View();
            }
        }

        public IActionResult CreateIngredient(RecipeStep s)
        {
            //recipeStep = new RecipeStep();

            if (recipeStep.Ingredients == null)
            {
                recipeStep.Ingredients = new List<Ingredient>();
            }

            recipeStep.Ingredients.Add(new Ingredient());

            return View();
        }

        [HttpPost]
        public IActionResult CreateIngredient(Ingredient i)
        {
            if (ModelState.IsValid)
            {

                recipeStep.Ingredients.Last().Name = i.Name;
                recipeStep.Ingredients.Last().Amount = i.Amount;
                recipeStep.Ingredients.Last().Unit = i.Unit;
                recipeStep.Ingredients.Last().SpecialInstructions = i.SpecialInstructions;

                return View("CreateStep", recipeStep);
            }
            else
            {
                return View();
            }
        }

    }
}

EZRecipize/Views/Cooking/Finshed.cshtml
@{
    ViewData["Title"] = "Finshed";
}

@model int
<br />
<div class="grayBox">
    <h1>Recipe Complete</h1>
    <h1>Enjoy your meal</h1>

    <form action="/" method="post">

        <button class="btn-hover color-8" asp-controller="Recipe" asp-action="RecipeDetails" asp-route-recipeId="@Model">Back to Details</button>
    </form>
</div>

EZRecipize/Views/Cooking/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model Recipe

<br />
    <div class="grayBox">
        <h1>Begin cooking @Model.RecipeName</h1>
        <form action="/" method="post">

            <button class="btn-hover color-8" asp-controller="Cooking" asp-action="Tutorial">Begin</button>
        </form>
    </div>

EZRecipize/Views/Cooking/Tutorial.cshtml
@{
    ViewData["Title"] = "RecipeCooking";
}

@model DisplayInfo

<br />
<div class="wrapper">
    <div class="RecipeBox TimerBox">
            <h2>Active Timers:</h2>
        @if (Model.timers.Count > 0)
        {
            foreach (KeyValuePair<string, int> timer in Model.timers)
            {
                <p>@timer.Key: @timer.Value min</p>
            }
        }
    </div>
    <div class="RecipeBox CookwareBox">
        <h3>Required Cookware:</h3>
        @if (Model.step.RequiredCookware != null)
        {
            @foreach (string s in Model.step.RequiredCookware)
            {
                <p>@s</p>
            }
        }

        <h3>Sugested Cookware:</h3>
        @if (Model.step.SuggestedCookware != null)
        {
            @foreach (string s in Model.step.SuggestedCookware)
            {
                <p>@s</p>
            }
        }
    </div>

    <div class="RecipeBox IngredientBox2">
        <h3>Ingredients:</h3>
        @if (Model.step.Ingredients != null)
        {
            @foreach (Ingredient i in Model.step.Ingredients)
            {
                <p>@i.Name @i.Amount @i.Unit (@i.SpecialInstructions)</p>
            }
        }
    </div>
    <br />
    <div class="RecipeBox StepsBox">
        <h3>Step:</h3>
        <p>@Model.step.Instructions</p>

        <form action="/" method="post">
            <button class="btn-hover color-8" asp-controller="Cooking" asp-action="Tutorial">NextStep</button>
        </form>

    </div>

</div>